# Generated by Django 3.1.2 on 2020-10-24 19:57

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='djangoClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('CourseNumber', models.IntegerField(max_length=5)),
                ('InstructorName', models.CharField(max_length=50)),
                ('Duration', models.FloatField(max_length=5)),
            ],
            managers=[
                ('djangoClasses', django.db.models.manager.Manager()),
            ],
        ),
    ]
